/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.Usuario;
import Utilidades.SesionUsuario;
import Utilidades.UtilidadUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author JocelioCalzon
 */
public class Inicio extends javax.swing.JFrame {
    
    private UtilidadUsuario utilidadUsuario;
    
    

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.utilidadUsuario = new UtilidadUsuario();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbl_icono = new javax.swing.JLabel();
        jbl_usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtx_usuario = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jlb_icono = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jlb_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Iniciar Sesión");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 30));

        jbl_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user (1).png"))); // NOI18N
        getContentPane().add(jbl_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jbl_usuario.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jbl_usuario.setForeground(new java.awt.Color(0, 51, 51));
        jbl_usuario.setText("Usuario");
        getContentPane().add(jbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jtx_usuario.setBackground(new java.awt.Color(204, 255, 255));
        jtx_usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtx_usuario.setForeground(new java.awt.Color(0, 153, 153));
        jtx_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtx_usuarioFocusGained(evt);
            }
        });
        jtx_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jtx_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 190, 30));

        jPassword.setBackground(new java.awt.Color(204, 255, 255));
        jPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPassword.setForeground(new java.awt.Color(0, 51, 51));
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 212, 190, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 440, 20));

        jlb_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        getContentPane().add(jlb_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Para registrar usuario ingresa al botón \"Registrar\"");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jlb_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/624986.jpg"))); // NOI18N
        getContentPane().add(jlb_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 725, 513));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtx_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_usuarioActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String usuario, contraseña;
        usuario = this.jtx_usuario.getText();
        if(usuario.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar el usuario", "validacion", 1);
            this.jtx_usuario.requestFocus();
            return;
        }
        
        contraseña = this.jPassword.getText();
        if(contraseña.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar contraseña", "validacion", 1);
            this.jtx_usuario.requestFocus();
            return;
        }
        
        boolean user; 
        
        user = utilidadUsuario.validarUser(usuario, contraseña);
        
        
        if(user == true){
            new menu().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrectos", "validacion", 1);
        }
        
       
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Registro().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtx_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtx_usuarioFocusGained
        this.jtx_usuario.setText("");
    }//GEN-LAST:event_jtx_usuarioFocusGained

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        this.jPassword.setText("");
    }//GEN-LAST:event_jPasswordFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbl_icono;
    private javax.swing.JLabel jbl_usuario;
    private javax.swing.JLabel jlb_fondo;
    private javax.swing.JLabel jlb_icono;
    private javax.swing.JTextField jtx_usuario;
    // End of variables declaration//GEN-END:variables

    private void setLocaltionRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
