/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.repositorioUser;
import Modelo.Usuario;
import Utilidades.UtilidadUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author JocelioCalzon
 */
public class Registro extends javax.swing.JFrame {
    
    private UtilidadUsuario utilidadUsuario;
    private repositorioUser repositorioUser;

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.utilidadUsuario = new UtilidadUsuario();
        this.repositorioUser = new repositorioUser();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbl_icono = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtx_nombre = new javax.swing.JTextField();
        jtx_apellido = new javax.swing.JTextField();
        jtx_usuario = new javax.swing.JTextField();
        jtx_password = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbl_icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acceso.png"))); // NOI18N
        getContentPane().add(jbl_icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 90, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Nombre :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Apellido :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 530, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Ingresa tus datos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Usuario : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 51));
        jLabel5.setText("Contraseña :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        jtx_nombre.setBackground(new java.awt.Color(204, 255, 255));
        jtx_nombre.setForeground(new java.awt.Color(153, 153, 153));
        jtx_nombre.setText("Ingresa tú nombre");
        jtx_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtx_nombreFocusGained(evt);
            }
        });
        jtx_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtx_nombreActionPerformed(evt);
            }
        });
        getContentPane().add(jtx_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 310, 30));

        jtx_apellido.setBackground(new java.awt.Color(204, 255, 255));
        jtx_apellido.setForeground(new java.awt.Color(153, 153, 153));
        jtx_apellido.setText("Ingresa tú apellido");
        jtx_apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtx_apellidoFocusGained(evt);
            }
        });
        getContentPane().add(jtx_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 310, 30));

        jtx_usuario.setBackground(new java.awt.Color(204, 255, 255));
        jtx_usuario.setForeground(new java.awt.Color(153, 153, 153));
        jtx_usuario.setText("Ingresa un nombre para el usuario");
        jtx_usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtx_usuarioFocusGained(evt);
            }
        });
        getContentPane().add(jtx_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 310, 30));

        jtx_password.setBackground(new java.awt.Color(204, 255, 255));
        jtx_password.setForeground(new java.awt.Color(153, 153, 153));
        jtx_password.setText("Ingresa una contraseña");
        jtx_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtx_passwordFocusGained(evt);
            }
        });
        getContentPane().add(jtx_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 310, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 140, 40));

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 140, 40));

        jbl_fondo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbl_fondo.setForeground(new java.awt.Color(255, 255, 255));
        jbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/624986.jpg"))); // NOI18N
        getContentPane().add(jbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Inicio().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtx_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtx_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtx_nombreActionPerformed

    private void jtx_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtx_nombreFocusGained
        this.jtx_nombre.setText("");
    }//GEN-LAST:event_jtx_nombreFocusGained

    private void jtx_apellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtx_apellidoFocusGained
        this.jtx_apellido.setText("");

    }//GEN-LAST:event_jtx_apellidoFocusGained

    private void jtx_usuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtx_usuarioFocusGained
        this.jtx_usuario.setText("");

    }//GEN-LAST:event_jtx_usuarioFocusGained

    private void jtx_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtx_passwordFocusGained
        this.jtx_password.setText("");

    }//GEN-LAST:event_jtx_passwordFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nombre, apellido, username, password;
        
        nombre = this.jtx_nombre.getText();
        if(nombre.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre", "Validacion", 1);
            this.jtx_nombre.requestFocus();
            return;
        }
        
        apellido = this.jtx_apellido.getText();
        if(apellido.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar un apellido", "Validacion", 1);
            this.jtx_apellido.requestFocus();
            return;
        }
        
        username = this.jtx_usuario.getText();
        if(username.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar un nombre de usuario", "Validacion", 1);
            this.jtx_usuario.requestFocus();
            return;
        }
        
        password = this.jtx_password.getText();
        if(password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Debes ingresar una contraseña", "Validacion", 1);
            this.jtx_password.requestFocus();
            return;
        }
        
        Usuario usuario = new Usuario(0, nombre, apellido, username, password);
        
        
        boolean estadoIngreso = repositorioUser.agregarUsuario(usuario);
        
        if(estadoIngreso == true){
            JOptionPane.showMessageDialog(this, "Se agrego usuario de forma exitosa", "Aviso", 1);
        }else{
            JOptionPane.showMessageDialog(this, "No se agrego usuario", "Aviso", 1);
        }
        
     
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jtx_nombre.setText("");
        this.jtx_apellido.setText("");
        this.jtx_usuario.setText("");
        this.jtx_password.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbl_fondo;
    private javax.swing.JLabel jbl_icono;
    private javax.swing.JTextField jtx_apellido;
    private javax.swing.JTextField jtx_nombre;
    private javax.swing.JTextField jtx_password;
    private javax.swing.JTextField jtx_usuario;
    // End of variables declaration//GEN-END:variables
}
